[package]
name = "xidl-node-test"
version = "0.0.0"
edition = "2024"
publish = false
[lib]
crate-type = ["cdylib"]
[workspace]
[dependencies]
xidl-node = { path = "../../crates/xidl-node" }
napi = { version = "3.14.2", default-features = false, features = ["napi8", "tokio_rt", "dyn-symbols"] }
napi-derive = "3.6.12"
[build-dependencies]
x_idl = { path = "../.." }
napi-build = "2.6.0"
