//! TypeScript bindings over an IDL-generated native transport.
use crate::{Declaration, RustTarget, generic, generic_pair, type_name};
use quote::ToTokens;
use std::collections::HashSet;
use syn::ext::IdentExt;
use syn::{FnArg, Item, ReturnType, TraitItem, Type};

/// TypeScript source for one binding. The native module implements `call`.
#[derive(Clone, Debug)]
pub struct Binding {
    pub source: String,
}

/// Generate TypeScript descriptors, enums, tagged events and resource wrappers.
/// No Node imports are emitted: the host supplies the native transport.
pub fn generate(
    namespace: &str,
    declaration: impl Into<Declaration>,
    webidl: &str,
) -> Result<Binding, String> {
    let declaration = declaration.into();
    let (model, _, plugin) = crate::generate_parts(
        namespace,
        &declaration,
        webidl,
        RustTarget::Node,
        &HashSet::new(),
    )?;
    let schema = schema(namespace, &model);
    let model = syn::parse_file(&model).map_err(crate::error)?;
    let declared = syn::parse_file(&declaration.text()?).map_err(crate::error)?;
    let mut out = String::from("// Generated by x-idl. Edit the binding declaration instead.\n\n");
    out.push_str(&format!("export const bindingSchema = \"{schema}\";\n"));
    out.push_str(
        "export interface NativeBinding { call(operation: number, args: unknown[]): unknown; }\n\n",
    );
    for item in &model.items {
        if let Item::Enum(e) = item {
            let name = e.ident.to_string();
            if plugin.unions.contains_key(&name) || plugin.variants.contains_key(&name) {
                continue;
            }
            // Native codes have already been checked and expanded from WebIDL.
            let values = enum_codes(&model, &name)?;
            out.push_str(&format!("export const {name} = {{\n"));
            for (variant, code) in values {
                out.push_str(&format!("  {variant}: {code},\n"));
            }
            out.push_str(&format!(
                "}} as const;\nexport type {name} = typeof {name}[keyof typeof {name}];\n\n"
            ));
        }
    }
    for item in &declared.items {
        if let Item::Enum(e) = item {
            let name = e.ident.to_string();
            if let Some(variants) = plugin.variants.get(&name) {
                out.push_str(&format!("export type {name} =\n"));
                for (v, fields) in variants {
                    out.push_str(&format!("  | {{ kind: \"{v}\""));
                    for (field, ty) in fields {
                        out.push_str(&format!("; {}: {}", field.unraw(), ts_type(ty, false)?));
                    }
                    out.push_str(" }\n");
                }
                out.push_str(";\n\n");
            } else if let Some(variants) = plugin.unions.get(&name) {
                out.push_str(&format!("export type {name} =\n"));
                for (v, ty, _) in variants {
                    out.push_str(&format!(
                        "  | {{ kind: \"{v}\"; value: {} }}\n",
                        ts_type(ty, false)?
                    ));
                }
                out.push_str(";\n\n");
            }
        }
    }
    for record in &plugin.records {
        out.push_str(&format!("export interface {} {{\n", record.class));
        for (field, ty, _) in &record.fields {
            let optional = generic(ty, "Option");
            // Empty sequences/maps have the same defaults as the native schema.
            let omittable = optional.is_some()
                || generic(ty, "Vec").is_some()
                || generic_pair(ty, "Map").is_some();
            let ty = optional.as_ref().unwrap_or(ty);
            out.push_str(&format!(
                "  {}{}: {};\n",
                field.unraw(),
                if omittable { "?" } else { "" },
                ts_type(ty, false)?
            ));
        }
        out.push_str("}\n\n");
    }
    let mut operations = Vec::new();
    let mut factories = Vec::new();
    let mut classes = String::new();
    for item in &declared.items {
        let Item::Trait(t) = item else { continue };
        let class = t.ident.to_string();
        out.push_str(&format!("export interface {class} {{\n"));
        classes.push_str(&format!("  class {class} {{\n    constructor(handle: unknown) {{ handles.set(this, handle); }}\n"));
        let mut statics = Vec::new();
        for method in &t.items {
            let TraitItem::Fn(f) = method else { continue };
            let mut args = Vec::new();
            let mut names = Vec::new();
            let mut receiver = false;
            for (i, input) in f.sig.inputs.iter().enumerate() {
                let FnArg::Typed(input) = input else {
                    return Err("explicit receivers required".into());
                };
                let syn::Pat::Ident(pat) = &*input.pat else {
                    return Err("named arguments required".into());
                };
                if i == 0
                    && matches!(&*input.ty, Type::Reference(r) if type_name(&r.elem).as_deref() == Some(&class))
                {
                    receiver = true;
                    names.push("handle(this)".to_owned());
                } else {
                    let name = parameter_name(&pat.ident.unraw().to_string());
                    args.push(format!("{name}: {}", ts_type(&input.ty, false)?));
                    names.push(encoded(&input.ty, &name, &plugin)?);
                }
            }
            let name = f.sig.ident.unraw().to_string();
            let ty: Type = match &f.sig.output {
                ReturnType::Default => syn::parse_quote!(()),
                ReturnType::Type(_, t) => (**t).clone(),
            };
            let member = if name == "new" { "\"new\"" } else { &name };
            let signature = format!("{member}({}): {};", args.join(", "), ts_type(&ty, true)?);
            if receiver {
                out.push_str(&format!("  {signature}\n"));
            } else {
                statics.push(signature);
            }
            let operation = operations.len();
            operations.push(format!("  \"{class}.{name}\": {operation},"));
            let call = format!("native.call({operation}, [{}])", names.join(", "));
            let value = returned(&ty, &call, &plugin.resources)?;
            classes.push_str(&format!(
                "    {}{name}({}): {} {{ return {value}; }}\n",
                if receiver { "" } else { "static " },
                args.join(", "),
                ts_type(&ty, true)?
            ));
        }
        out.push_str("}\n\n");
        classes.push_str("  }\n");
        factories.push((class, statics));
    }
    // Constants are expanded in the model as associated zero-argument methods.
    for item in &declared.items {
        if let Item::Mod(m) = item {
            let class = &m.ident;
            out.push_str(&format!("export const {class} = {{\n"));
            for item in &model.items {
                if let Item::Impl(i) = item {
                    if type_name(&i.self_ty).as_deref() != Some(&class.to_string()) {
                        continue;
                    }
                    for item in &i.items {
                        let syn::ImplItem::Fn(f) = item else { continue };
                        out.push_str(&format!(
                            "  {}: {},\n",
                            f.sig.ident.unraw(),
                            f.block
                                .stmts
                                .iter()
                                .map(ToTokens::to_token_stream)
                                .map(|s| s.to_string())
                                .collect::<String>()
                        ));
                    }
                }
            }
            out.push_str("} as const;\n\n");
        }
    }
    out.push_str(&format!(
        "export const operations = {{\n{}\n}} as const;\n\n",
        operations.join("\n")
    ));
    out.push_str("export interface Bindings {\n");
    for (class, methods) in &factories {
        out.push_str(&format!("  {class}: {{ {} }};\n", methods.join(" ")));
    }
    out.push_str("}\n\nexport function bind(native: NativeBinding): Bindings {\n  if (native.call(4294967295, []) !== bindingSchema) throw new Error(\"Native binding schema mismatch; rebuild the addon and TypeScript bindings together\");\n");
    out.push_str("  const handles = new WeakMap<object, unknown>();\n  function handle(value: object): unknown {\n    if (!handles.has(value)) throw new TypeError(\"expected a resource from this binding\");\n    return handles.get(value);\n  }\n");
    for record in &plugin.records {
        out.push_str(&format!(
            "  function encode_{}(value: {}): unknown {{\n    return {{\n",
            record.class, record.class
        ));
        for (field, ty, _) in &record.fields {
            let name = field.unraw().to_string();
            out.push_str(&format!(
                "      {name}: {},\n",
                encoded(ty, &format!("value.{name}"), &plugin)?
            ));
        }
        out.push_str("    };\n  }\n");
    }
    for item in &declared.items {
        let Item::Enum(e) = item else { continue };
        let name = e.ident.to_string();
        if let Some(variants) = plugin.unions.get(&name) {
            out.push_str(&format!(
                "  function encode_{name}(value: {name}): unknown {{\n    switch (value.kind) {{\n"
            ));
            for (variant, ty, _) in variants {
                out.push_str(&format!(
                    "      case \"{variant}\": return {{ kind: value.kind, value: {} }};\n",
                    encoded(ty, "value.value", &plugin)?
                ));
            }
            out.push_str(&format!("      default: throw new TypeError(\"unknown {name} alternative\");\n    }}\n  }}\n"));
        }
    }
    out.push_str(&classes);
    out.push_str(&format!(
        "  return {{ {} }};\n}}\n",
        factories
            .iter()
            .map(|(c, _)| c.as_str())
            .collect::<Vec<_>>()
            .join(", ")
    ));
    Ok(Binding { source: out })
}

fn enum_codes(file: &syn::File, name: &str) -> Result<Vec<(String, String)>, String> {
    for item in &file.items {
        let Item::Impl(i) = item else { continue };
        if type_name(&i.self_ty).as_deref() != Some(name) || i.trait_.is_some() {
            continue;
        }
        for item in &i.items {
            let syn::ImplItem::Fn(f) = item else { continue };
            if f.sig.ident != "native" {
                continue;
            }
            let Some(syn::Stmt::Expr(syn::Expr::Match(m), _)) = f.block.stmts.first() else {
                continue;
            };
            return m
                .arms
                .iter()
                .map(|a| {
                    let syn::Pat::Path(p) = &a.pat else {
                        return Err("invalid generated enum".into());
                    };
                    Ok((
                        p.path.segments.last().unwrap().ident.unraw().to_string(),
                        a.body.to_token_stream().to_string(),
                    ))
                })
                .collect();
        }
    }
    Err(format!("missing native enum {name}"))
}

pub(crate) fn ts_type(ty: &Type, result: bool) -> Result<String, String> {
    if let Type::Reference(r) = ty {
        return ts_type(&r.elem, result);
    }
    if matches!(ty, Type::Tuple(t) if t.elems.is_empty()) {
        return Ok("void".into());
    }
    if let Some(inner) = generic(ty, "Option") {
        return Ok(format!("{} | null | undefined", ts_type(&inner, result)?));
    }
    if let Some(inner) = generic(ty, "Vec") {
        return Ok(format!("Array<{}>", ts_type(&inner, result)?));
    }
    if let Some((k, v)) = generic_pair(ty, "Map") {
        return Ok(format!(
            "Map<{}, {}>",
            ts_type(&k, false)?,
            ts_type(&v, false)?
        ));
    }
    if let Some(inner) = generic(ty, "Enum").or_else(|| generic(ty, "Box")) {
        return ts_type(&inner, result);
    }
    if let Some(inner) = generic(ty, "Future") {
        let nullable = type_name(&inner).is_some();
        return Ok(format!(
            "Promise<{}{}>",
            ts_type(&inner, true)?,
            if nullable { " | null" } else { "" }
        ));
    }
    Ok(
        match type_name(ty)
            .ok_or_else(|| format!("unsupported TypeScript type {}", ty.to_token_stream()))?
            .as_str()
        {
            "i32" | "u32" | "f32" | "f64" => "number".into(),
            "i64" | "u64" => "bigint".into(),
            "bool" => "boolean".into(),
            "Text" if result => "string | null".into(),
            "Text" => "string".into(),
            "Buffer" if result => "Uint8Array | null".into(),
            "Buffer" | "BufferMut" => "Uint8Array".into(),
            other => other.to_owned(),
        },
    )
}

fn returned(ty: &Type, call: &str, resources: &HashSet<String>) -> Result<String, String> {
    if let Some(inner) = generic(ty, "Future") {
        let result = if let Some(name) = type_name(&inner).filter(|n| resources.contains(n)) {
            format!("value == null ? null : new {name}(value)")
        } else {
            format!("value as {}", ts_type(&inner, true)?)
        };
        return Ok(format!(
            "({call} as Promise<unknown>).then(value => {result})"
        ));
    }
    if let Some(inner) = generic(ty, "Box") {
        let name = type_name(&inner).ok_or("named resource result")?;
        return Ok(format!("new {name}({call})"));
    }
    Ok(format!("{call} as {}", ts_type(ty, true)?))
}

// Generate schema-specific conversion only where a descriptor contains native
// resources. Primitive arguments and byte views pass straight to the addon.
fn encoded(ty: &Type, value: &str, plugin: &crate::convert::Plugin) -> Result<String, String> {
    if let Type::Reference(r) = ty {
        return encoded(&r.elem, value, plugin);
    }
    if let Some(inner) = generic(ty, "Option") {
        let converted = encoded(&inner, &format!("({value})!"), plugin)?;
        return Ok(format!("{value} == null ? undefined : {converted}"));
    }
    if let Some(inner) = generic(ty, "Vec") {
        return Ok(format!(
            "({value} ?? []).map(item => {})",
            encoded(&inner, "item", plugin)?
        ));
    }
    if let Some((k, v)) = generic_pair(ty, "Map") {
        return Ok(format!(
            "[...({value} ?? [])].map(([key, item]) => [{}, {}])",
            encoded(&k, "key", plugin)?,
            encoded(&v, "item", plugin)?
        ));
    }
    if generic(ty, "Enum").is_some() {
        return Ok(value.to_owned());
    }
    let Some(name) = type_name(ty) else {
        return Ok(value.to_owned());
    };
    if plugin.resources.contains(&name) {
        return Ok(format!("handle({value})"));
    }
    if plugin.records.iter().any(|r| r.class == name.as_str()) || plugin.unions.contains_key(&name)
    {
        return Ok(format!("encode_{name}({value})"));
    }
    Ok(value.to_owned())
}

fn parameter_name(name: &str) -> String {
    if matches!(
        name,
        "arguments"
            | "eval"
            | "protected"
            | "private"
            | "public"
            | "implements"
            | "interface"
            | "package"
            | "yield"
            | "await"
            | "let"
            | "static"
            | "super"
            | "default"
            | "class"
            | "function"
            | "var"
            | "const"
            | "import"
            | "export"
            | "enum"
            | "extends"
            | "return"
            | "void"
            | "null"
            | "true"
            | "false"
            | "this"
    ) {
        format!("value_{name}")
    } else {
        name.to_owned()
    }
}

// Detect accidentally mixing independently generated native/TypeScript APIs.
// This is a deterministic compatibility fingerprint, not a security hash.
pub(crate) fn schema(namespace: &str, model: &str) -> String {
    let mut hash = 0xcbf29ce484222325u64;
    for byte in model.bytes() {
        hash = (hash ^ byte as u64).wrapping_mul(0x100000001b3);
    }
    format!("xidl:{namespace}:{hash:016x}")
}
